#!/usr/bin/env python3
"""
Review Report Generator
Aggregates findings into a professional Markdown report.
"""

import argparse
import sys
import json
from pathlib import Path
from datetime import datetime

def generate_report(findings_path: Path, verbose: bool = False):
    """Generate a report from findings."""
    if not findings_path.exists():
        return f"❌ Findings path does not exist: {findings_path}"

    all_findings = []
    
    # Load findings
    if findings_path.is_file():
        try:
            data = json.loads(findings_path.read_text(encoding="utf-8"))
            all_findings = data if isinstance(data, list) else [data]
        except Exception as e:
            return f"❌ Failed to parse findings file: {e}"
    else:
        # Scan directory for json files
        for json_file in findings_path.glob("*.json"):
            try:
                data = json.loads(json_file.read_text(encoding="utf-8"))
                all_findings.extend(data if isinstance(data, list) else [data])
            except:
                pass

    if not all_findings:
        return "ℹ️ No findings to report."

    # Build Markdown
    report = [
        "# Code Review Synthesis Report",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "\n## Summary",
        f"Total findings: {len(all_findings)}",
        "\n| File | Type | Severity/Impact | Message |",
        "| --- | --- | --- | --- |"
    ]

    for f in all_findings:
        # Handle variations in finding structure from different scripts
        file_path = f.get('file', 'N/A')
        f_type = f.get('type', 'Standard')
        severity = f.get('severity') or f.get('impact', 'Medium')
        message = f.get('message', 'No detail provided')
        
        report.append(f"| `{file_path}` | {f_type} | **{severity}** | {message} |")

    report.append("\n\n---\n*Report generated by Swiss Intel Code Reviewer Skill*")
    return "\n".join(report)

def main():
    parser = argparse.ArgumentParser(
        description="Review Report Generator - Swiss Intel Edition"
    )
    parser.add_argument(
        "findings_path",
        type=Path,
        help="Path to findings file or directory containing JSON results"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose output"
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        help="Output file path (default: stdout)"
    )

    try:
        args = parser.parse_args()
        report = generate_report(args.findings_path, args.verbose)
        
        if args.output:
            args.output.write_text(report)
            print(f"Report written to {args.output}")
        else:
            print(report)
            
        sys.exit(0)
            
    except PermissionError:
        print("❌ Permission denied accessing path")
        sys.exit(2)
    except KeyboardInterrupt:
        print("\n⚠️ Interrupted by user")
        sys.exit(3)
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        sys.exit(4)

if __name__ == "__main__":
    main()
